name: Release

on:
  workflow_dispatch:
    inputs:
      myinput:
        type: string 
        description: Java Version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '${{ inputs.myinput}}'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true
  
      - name: Upload jar to folder
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/

